name: Check codebase using Sourcery

on:
  push:
    branches: [master]

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.WIFITE }}
